[package]
name = "librashader-runtime-d3d9"
edition = "2021"

license = "MPL-2.0 OR GPL-3.0-only"
version = "0.2.4"
authors = ["Ronny Chan <ronny@ronnychan.ca>"]
repository = "https://github.com/SnowflakePowered/librashader"
readme = "../README.md"
categories = ["emulators", "compilers", "graphics"]
keywords = ["shader", "retroarch", "SPIR-V"]
description = "RetroArch shaders for all."

[dependencies]
librashader-common = { path = "../librashader-common", features = ["d3d9", "d3d11"], version = "0.2.4" }
librashader-presets = { path = "../librashader-presets", version = "0.2.4" }
librashader-preprocess = { path = "../librashader-preprocess", version = "0.2.4" }
librashader-reflect = { path = "../librashader-reflect", version = "0.2.4" }
librashader-runtime = { path = "../librashader-runtime", version = "0.2.4" }
librashader-cache = { path = "../librashader-cache", version = "0.2.4", features = ["d3d"] }

thiserror = "1.0.37"
bytemuck = "1.12.3"
array-concat = "0.5.2"
num-traits = "0.2.18"

[target.'cfg(windows)'.dependencies.windows]
workspace = true
features = [
    "Win32_Foundation",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D9",
    "Win32_Graphics_Direct3D_Fxc",
    "Win32_System_Threading",
    "Win32_Security",
    "Foundation_Numerics"
]

[target.'cfg(windows)'.dev-dependencies.windows]
workspace = true
features = [
    "Win32_Foundation",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D9",
    "Win32_Graphics_Direct3D9on12",
    "Win32_Graphics_Direct3D_Fxc",
    "Win32_Graphics_Gdi",
    "Win32_Security",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI",
    "Foundation_Numerics"
]

[[test]]
name = "triangle"

[dev-dependencies]
gfx-maths = "0.2.8"

[package.metadata.docs.rs]
features = ["librashader-cache/docsrs"]
