[package]
name = "librashader-build-script"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
cbindgen = "0.27.0"
clap = { workspace = true }
carlog = "0.1.0"

[package.metadata.release]
release = false
