[package]
name = "librashader-pack"
version = "0.5.1"
edition = "2021"
license = "MPL-2.0 OR GPL-3.0-only"
authors = ["Ronny Chan <ronny@ronnychan.ca>"]
repository = "https://github.com/SnowflakePowered/librashader"
readme = "../README.md"
categories = ["emulators", "compilers", "graphics"]
keywords = ["shader", "retroarch", "SPIR-V"]
description = "RetroArch shaders for all."

[dependencies]
librashader-presets = { path = "../librashader-presets", version = "0.5.1", features = ["serde"] }
librashader-preprocess = { path = "../librashader-preprocess", version = "0.5.1", features = ["serde"] }

thiserror = "2"
serde = { version = "1.0", features = ["derive"], optional = true }
rayon = { workspace = true }
image = {workspace = true}
base64 = {  version = "0.22.1", optional = true }
serde_bytes = { version = "0.11.15", optional = true }

[features]
parse_legacy_glsl = ["librashader-presets/parse_legacy_glsl"]
serde = ["dep:serde", "dep:base64", "dep:serde_bytes"]

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
rayon = { workspace = true }

[dev-dependencies]
anyhow = "1.0.89"
serde_json = "1.0.128"
rmp-serde = "1.3.0"
